services:
  - type: web
    name: ai-attendance-server
    plan: free
    env: docker
    rootDir: server
    envVars:
      - key: PORT
        value: 8085

  - type: static
    name: ai-attendance-client
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/dist
    envVars:
      - key: VITE_API_URL
        value: https://ai-attendance-server.onrender.com
